### PR TITLE
Allow setting -1 as seed for random

### PR DESCRIPTION
**Pull request by scarbain**
Hi! As it was asked by multiple persons, I made the modifications to set -1 on gradio interfaces and select a random int when set.

### CODE REVIEW

**Comment by lllyasviel** [comment]
nice trick

**Comment by FurkanGozukara** [comment]
@scarbain awesome. Can you also add infinite generate and save output options?

**Comment by scarbain** [comment]
I can but @lllyasviel shouldn't we factor the code so that we don't have to repeat changes to all gradio interfaces ?
If you want I can make a single python file that will take an argument as what models should be used

**Comment by FurkanGozukara** [comment]
> I can but @lllyasviel shouldn't we factor the code so that we don't have to repeat changes to all gradio interfaces ? If you want I can make a single python file that will take an argument as what models should be used

That makes much more sense

**Pull request merged**
