### PR TITLE
fix a bug for DDIM inversion (DDIMSampler.encode())

### PR DESCRIPTION
**Pull request by williamyang1991**
fix a bug of the incorrect timestep in DDIMSampler.encode() for DDIM inversion

t is incorrectly set as the index of timesteps rather than the timestep in the original code.

### CODE REVIEW

**Comment by lllyasviel** [comment]
but this file is copied from stability's SD 2. Is that code also incorrect?

**Comment by williamyang1991** [comment]
I look into the code of SD 2 just now, and it seems that the original code has the same bug. 
I will report this bug in SD 2.

https://github.com/Stability-AI/stablediffusion/blob/cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf/ldm/models/diffusion/ddim.py#L273

**Comment by lllyasviel** [comment]
wait a minute do we really called this function in the entire controlnet project?

**Comment by williamyang1991** [comment]
your code didn't call it.
I just played with controlnet for some edge-guided image editings.
For image editing, I need image inversion, so I used the encode() and found this bug.

**Comment by moegi161** [comment]
@williamyang1991 @lllyasviel 
Hello, I am also trying to use ControlNet with DDIM inversion.
In the `encode()` function,
https://github.com/lllyasviel/ControlNet/blob/d3284fcd0972c510635a4f5abe2eeb71dc0de524/cldm/ddim_hacked.py#L257-L260


The above code assumes `unconditional_conditioning` and `c` as Tensors, but the `apply_model()` in ControlLDM asserts them as dict.
https://github.com/lllyasviel/ControlNet/blob/d3284fcd0972c510635a4f5abe2eeb71dc0de524/cldm/cldm.py#L329

Have you encountered any problems with this? Or Am I misunderstanding something?
Thank you very much.

**Comment by williamyang1991** [comment]
@moegi161 I just use `unconditional_guidance_scale=1.0`, with `c={'c_concat': None, 'c_crossattn': [model.get_learned_conditioning([""] * num_samples)]}`

**Comment by theohsiung** [comment]
Hi @williamyang1991 I'm also trying to use controlnet for image editing can you show me how you use it?

**Comment by Tranquil1ty** [comment]
for i in tqdm(range(num_steps), desc='Encoding Image'):
            t = torch.full((x0.shape[0],), timesteps[i], device=self.model.device, dtype=torch.long)
            if unconditional_guidance_scale == 1.:
                noise_pred = self.model.apply_model(x_next, t, c)
            else:
                assert unconditional_conditioning is not None
                merged_dict={}
                for key in unconditional_conditioning.keys():    
                    if unconditional_conditioning[key] is not None and c[key] is not None:
                        merged_list = [torch.cat((unconditional_conditioning[key][0],c[key][0]))]  
                        merged_dict[key] = merged_list       
                    else:
                       merged_dict[key]=None
                           
                e_t_uncond, noise_pred = torch.chunk(
                    self.model.apply_model(torch.cat((x_next, x_next)), torch.cat((t, t)),
                                        merged_dict ), 2)
                noise_pred = e_t_uncond + unconditional_guidance_scale * (noise_pred - e_t_uncond)
Hi, I try to fix the error when unconditional guidance scale is not 1. The code works well but I can't sure it is right.
@williamyang1991 Perhaps you can merge this code？

**Pull request merged**
