### PR TITLE
please use vram

### PR DESCRIPTION
**Pull request by camenduru**

### CODE REVIEW

**Comment by FurkanGozukara** [comment]
what affect does this change make?

**Comment by lllyasviel** [comment]
this is not safe. let us say user has 8 gb vram, and the model is 4.1gb, then if model is loaded before state dict, the free vram is 3.9gb. which is not enough for loading state dict. 
loading both model and state dict in cpu and then move it to gpu is safer

**Comment by camenduru** [comment]
free colab only 12.7 GB we are crashing  😭

**Comment by camenduru** [comment]
it is loading to cpu then gpu 😐

**Comment by lllyasviel** [comment]
12.7 GB mem? that should be able to load both model and state dict in cpu

**Comment by camenduru** [comment]
please delete !git clone `-b cuda` https://github.com/camenduru/ControlNet and try `gradio_hough2image.py`

https://github.com/camenduru/controlnet-colab/blob/main/controlnet-colab.ipynb

**Comment by lllyasviel** [comment]
can model on cpu directly load gpu state dict? if that happens, the model is cpu or gpu?

**Comment by camenduru** [comment]
`model.load_state_dict(load_state_dict('./models/control_sd15_canny.pth', location='cpu'))` first go to ram 
`model = model.cuda()` then go to vram

**Comment by lllyasviel** [comment]
but

model = create_model('./models/cldm_v15.yaml').cpu() # model is on cpu 
model.load_state_dict(load_state_dict('./models/control_sd15_canny.pth', location='cuda')) # cpu model loading gpu state_dict. Is this an encouraged behavior in pytorch?

**Comment by camenduru** [comment]
lol interesting

**Comment by camenduru** [comment]
model = create_model('./models/cldm_v15.yaml').cpu() # model is on cpu 
`yaml`

**Comment by camenduru** [comment]
@FurkanGozukara naber 👋

**Comment by camenduru** [comment]
maybe we need garbage collection or something idk

**Comment by lllyasviel** [comment]
will consider later

**Comment by camenduru** [comment]
with this everything works nice 
Screenshot 2023-02-13 025325

**Comment by lllyasviel** [comment]
But introducing undefined behavior may bind the project to a certain version of pytorch. The behavior of pytorch toward this may or may not change – for example – they may convert everything to cpu when cpu model is loading state dict wherever it is stored, or they just making the model to gpu, or they can have mixed status like this

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara naber 👋

thanks fine

prepared the first tutorial video : https://youtu.be/YJebdQ30UZQ

I think we need auto save generated image output into a folder - already i got a comment asking that

also infinite generation - or a batch count like generate 10000 images - set able like in web ui

**Comment by lllyasviel** [comment]
After many considerations, this request is merged

**Pull request merged**
